### ISSUE TITLE
Set extbase.controllerExtensionName

### ISSUE THREAD

**Issue by georgringer** [b13/bolt#10]
It would be cool to set `lib.contentElement.extbase.controllerExtensionName` to name of site package

**Comment by josefglatz** [comment]
According to your plans @bmack this issue can be closed as you want to / will remove the "option"?

**Comment by bmack** [comment]
this might be conflicting and have a few side effects (at least in our projects) to apply further defaults. Maybe we could add this to TYPO3 in FLUIDTEMPLATE to "guess" an extension name?
