### ISSUE TITLE
Permit to override TypoScript

### ISSUE THREAD

**Issue by asakurayoh** [b13/bolt#15]
We came across a problem in our site.
Bolt load the TypoScript completely at the end of the chain, so any template added on a page can't override TypoScript defined... 
Is that wished? I think bolt should load the TypoScript before the templates defined on a page... in first...
Now If I want to override something, I need a condition in the site TypoScript...

Thanks.

**Comment by achimfritz** [comment]
that is wished. no TS in DB, use condition in TS-File

**Comment by ftrojahn** [comment]
Just wanted to let you know, that we sadly had to abandon the use of ext:bolt in a large multisite project.
We found no way to let support people set e.g. pageids per Domain in TYPO3 backend. 
Neither by constant editor nor by editing custom settings added in siteconfig.

**Comment by georgringer** [comment]
see https://github.com/b13/bolt/pull/38, should now work again
