### ISSUE TITLE
Question: How to use same sitepackage for multiple websites?

### ISSUE THREAD

**Issue by typecat** [b13/bolt#20]
I very much would love to use this extension in a huge project with multiple websites. The particular use case is, that they all share the same sitepackage, because it's only a few site tree specific overrides (like TypoScript constants or PAGE_TSCONFIG_ID) per package. So far I stored those overrides in a specific sub-folder inside the sitepackage and included the file in the TypoScript Template Object record, e.g.
`<INCLUDE_TYPOSCRIPT: source="FILE:EXT:my_sitepackage/Configuration/TypoScript/sites/website-a/constants.typoscript">`

Unfortunately, the paths where bolt looks for configuration are fixed. So here's my question: 

Is it possible to make them adjustable? Or, what would be a better way to handle this (except having a sitepackage per site tree, because I don't see a benefit in having 20 site packages with only some constant overrides inside)?

**Comment by bmack** [comment]
Hey @typecat ,

I recently experienced the same topic in a v11 project. What I did:

1. Used the main site configuration with the defaults in all site configuration yaml files. e.g. "sitePackage: my_base_site".
2. Moved all differences between each page trees to site settings, In the site configuration via "settings.pages.search = 123". These are then available as constants and in PageTS conditions in all sites, or "settings.enableNews = true" so the site package was not aware of any page IDs or any other special options.

But this depends on the use-case.

In some projects, I do have a site package per pagetree, where the site packages only extend the "my_base_site" TypoScript (via "@import") and only override the values needed.

**Comment by achimfritz** [comment]
Hi @typecat use one site-package and use site-settings instead of TypoScript Constants (can also be used in PageTs), s. https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/SiteHandling/SiteSettings.html

**Comment by typecat** [comment]
Thanks @bmack, I wasn't aware of the site settings - great!

Unfortunately now I'm stuck with a different issue: I'm using the [lib.dynamicContent](https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/TypoScript/ContentElement/Helper/DynamicContent.typoscript) of EXT:bootstrap_package (but not the extension itself) to render a column's content elements. The HTML of RTE formatted text fields (e.g. CType text) is rendered as a string, which results in the markup being displayed in the frontend.

I checked:
* `lib.parseFunc` and `lib.parseFunc_RTE` configurations are included
* RTE setup is registered and the preset is assigned
* The template renders the text with  `f:format.html`

The setup works perfectly without bolt. Do you have an idea what I might be doing wrong?

**Comment by typecat** [comment]
I found the problem, it was in my includes structure. The setup works fine now! Sorry for bothering >.<
