### ISSUE TITLE
v12: Hide Typoscript Submodules

### ISSUE THREAD

**Issue by h3nn3s** [b13/bolt#32]
Since v12.0 it is not possible anymore to disable submodules by pageTs:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-97135-RemovedSupportForModuleHandlingBasedOnTBE_MODULES_EXT.html

Therefore your code stopped working 
```
mod.web_ts.menu.function.tx_tstemplateceditor = 0
 mod.web_ts.menu.function.tx_tstemplateinfo = 0
```

The new way to hide submodules is by using UserTS in your ext_tables.php:
```
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addUserTSConfig('
options.hideModules := addToList(web_typoscript_infomodify, web_typoscript_constanteditor)
');
```

**Comment by lolli42** [comment]
Yeah. Saw this as well. We should streamline before releasing a v12 compat version of the extension.
