### ISSUE TITLE
TYPO3\CMS\Extbase\ConfigurationBackendConfigurationManager getTypoScriptSetup() broken in Typo3 v12

### ISSUE THREAD

**Issue by abvdveen** [b13/bolt#39]
Due to the rewriting of function getTypoScriptSetup() in V12, this function no longer returns any Typoscript that is included using Bolt. Only when you use the constants or setup field in the TS template of the site, or include static templates directly, will you get any Typoscript.

**Comment by abvdveen** [comment]
Are you planning a fix for this?

**Comment by achimfritz** [comment]
no,  TypoScript is not for TYPO3 Backend, but you can use EXT:my_extension/ext_typoscript_setup.typoscript 
s. https://docs.typo3.org/m/typo3/reference-typoscript/12.4/en-us/TopLevelObjects/Module.html

(sorry for delayed answer)
